# Making a kNN for classification

## Pseudo Code:
* Testing point is xte
* For each training data point xtr:
    * measure    distance(xte to xtr)
* End for loop -> O(n) time complexity
* Sort distances -> O(nlog n) time complexity
* Select k nearest points
* Assign most common class (mode)

In [1]:
# import relevant packages
import numpy as np
from statistics import mode
import time
import matplotlib.pyplot as plt

In [2]:
# import x train data
training_data = np.loadtxt('optdigits.tra', delimiter=',')
print(training_data, type(training_data), training_data.shape)

# need to extract the class attribute (last digit) from all 3823 training examples

# use classes to keep y associated with each x train point?
# create object of each xtrain data set

[[ 0.  1.  6. ...  0.  0.  0.]
 [ 0.  0. 10. ...  0.  0.  0.]
 [ 0.  0.  8. ...  0.  0.  7.]
 ...
 [ 0.  0.  3. ...  0.  0.  6.]
 [ 0.  0.  6. ...  5.  0.  6.]
 [ 0.  0.  2. ...  0.  0.  7.]] <class 'numpy.ndarray'> (3823, 65)


In [3]:
# extract features and digits as X and y using list comprehension:
X_train = [example[0:-1] for example in training_data]
y_train = [example[-1] for example in training_data]
# print(len(X), X)
# print(len(y), y)

In [4]:
# import and store test data
test_data = np.loadtxt('optdigits.tes', delimiter=',')
X_test = [example[0:-1] for example in test_data]
y_test = [example[-1] for example in test_data]

In [5]:
# define a model class with all the relevant methods
class kNN:
    
    def __init__(self, n, p):
        self.n = n
        self.minkowski_power = p
        self.incorrectly_classified = []
    
    def fit(self, x_train, y_train):
        self.x_train = x_train
        self.y_train = y_train
        
    def predict(self, test_data):
        self.X_test = test_data
        # create empty list that will be filled with distances (same length as test features)
        self.y_pred = np.zeros(len(self.X_test))
        
        # use a for loop to complete this process on each element in self.x_test
        for i in range(len(self.X_test)):
            distance = np.power(np.sum(np.power(np.abs((self.X_test[i]-self.x_train)), self.minkowski_power),\
                                       axis=1), (1/self.minkowski_power))
            distance_sorted = distance.argsort()
            # returns an array of indices that would sort an array - allows you to retain the original order 
        
            # find the most common target of the first n numbers of the y_train set and assign to the y_test array
            # create empty array of closest points (length n)
            closest_points = np.zeros(self.n)
            # assign first five points of closest_points as the y_train values with indices of 0-n in distance_sorted
            for j in range(0, self.n):
                closest_points[j] = (y_train[distance_sorted[j]])
            
            self.y_pred[i] = mode(closest_points)
        # this is rewriting the original test data so need to store that separately and then compare at the end
        return self.y_pred
    
    def accuracy(self, y_test):
        self.y_test = y_test
        correct = 0
        incorrect = 0
        
        for i in range(len(self.y_test)):
            if self.y_test[i] == self.y_pred[i]:
                correct += 1
            else:
                incorrect += 1
                # only adds the incorrect labels to the list - should add both the features and the label
                self.incorrectly_classified.append(self.y_pred[i])
        
        self.model_accuracy = (correct/(incorrect + correct))*100
        return self.model_accuracy

In [6]:
#create instance of kNN model, specifying the number of neighbours
# minkowski_power = 1
neighbours = 5
model_euclidean = kNN(neighbours, 2)
model_manhattan = kNN(neighbours, 1)

In [7]:
# use model to train data and test timings
start_train_time_e = time.time()
model_euclidean.fit(X_train, y_train)
end_train_time_e = time.time()
train_time_euclidean = end_train_time_e - start_train_time_e

start_predict_time_e = time.time()
test_classes = model_euclidean.predict(X_test)
end_predict_time_e = time.time()
test_time_euclidean = end_predict_time_e - start_predict_time_e

accuracy_e = model_euclidean.accuracy(y_test)

In [8]:
# use model to train data and test timings
start_train_time_m = time.time()
model_manhattan.fit(X_train, y_train)
end_train_time_m = time.time()
train_time_manhattan = end_train_time_m - start_train_time_m

start_predict_time_m = time.time()
test_classes = model_manhattan.predict(X_test)
end_predict_time_m = time.time()
test_time_manhattan = end_predict_time_m - start_predict_time_m

accuracy_m = model_manhattan.accuracy(y_test)

In [9]:
print('Time taken to train the model: {:.4f} s'.format(train_time_euclidean))
print('Time taken to run the model: {:.4f} s'.format(test_time_euclidean))
print('Model accuracy with {} Nearest Neighbours and Euclidean distance is: {:.2f}%'.format(model_euclidean.n, accuracy_e))

Time taken to train the model: 0.0000 s
Time taken to run the model: 18.1670 s
Model accuracy with 5 Nearest Neighbours and Euclidean distance is: 97.83%


In [10]:
print('Time taken to train the model: {:.4f} s'.format(train_time_manhattan))
print('Time taken to run the model: {:.4f} s'.format(test_time_manhattan))
print('Model accuracy with {} Nearest Neighbours and Manhattan distance is: {:.2f}%'.format(model_manhattan.n, accuracy_m))

Time taken to train the model: 0.0000 s
Time taken to run the model: 18.4712 s
Model accuracy with 5 Nearest Neighbours and Manhattan distance is: 97.33%


In [11]:
print(model_euclidean.incorrectly_classified)

[1.0, 9.0, 1.0, 1.0, 1.0, 1.0, 1.0, 9.0, 9.0, 9.0, 9.0, 9.0, 5.0, 9.0, 8.0, 6.0, 8.0, 4.0, 4.0, 1.0, 1.0, 1.0, 3.0, 8.0, 7.0, 3.0, 9.0, 3.0, 8.0, 1.0, 7.0, 8.0, 3.0, 5.0, 8.0, 1.0, 5.0, 1.0, 1.0]
