In [1]:
# import relevant packages
import numpy as np
import mnist_reader

In [2]:
# load data sets
X_train, y_train = mnist_reader.load_mnist('.', kind='train')
X_test, y_test = mnist_reader.load_mnist('.', kind='t10k')

In [3]:
# see what data strucutre looks like
print(X_train, y_train)
print(type(X_train), X_train.shape)
print(type(X_test), X_test.shape)
print(type(y_train), y_train.shape)
print(type(y_test), y_test.shape)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]] [9 0 0 ... 3 0 5]
<class 'numpy.ndarray'> (60000, 784)
<class 'numpy.ndarray'> (10000, 784)
<class 'numpy.ndarray'> (60000,)
<class 'numpy.ndarray'> (10000,)


In [4]:
t_shirt = 0
trousers = 1
pullover = 2
dress = 3
coat = 4
sandal = 5
shirt = 6
sneaker = 7
bag = 8
ankle_boot = 9

In [5]:
# create function to separate different pairs of clothes, passing in the clothes labels as the last two parameters
# the first label passed will be relabeled as -1

def filter_datasets(X_train,X_test, y_train, y_test, clothes1, clothes2):
    # training sets
    filtered_y_train_indices = np.where((y_train == clothes1)| (y_train == clothes2))[0].tolist()
    
    filtered_y_train = []
    filtered_x_train = []
    
    for i in filtered_y_train_indices:
        filtered_y_train.append(y_train[i])
        filtered_x_train.append(X_train[i])
    
    # make into np.arrays
    filtered_y_train = np.array(filtered_y_train)
    filtered_x_train = np.array(filtered_x_train)
    
    print(filtered_y_train)
#     print(filtered_x_train)
    
    # recode the y labels to be -1 and 1
    filtered_y_train = np.where(filtered_y_train == clothes1, -1, filtered_y_train)
    filtered_y_train = np.where(filtered_y_train == clothes2, 1, filtered_y_train)
    print(filtered_y_train)
    
    
    # test sets
    filtered_y_test_indices = np.where((y_test == clothes1)| (y_test == clothes2))[0].tolist()
#     print(filtered_y_test_indices)
#     print(len(filtered_y_test_indices))
    # print('the indices of y_train corresponding to t-shirts (0) and trousers(1):{}'.format(filtered_y_train_indices))

    # use these indices to segment x_test to only show these features
    filtered_y_test = []
    filtered_x_test = []

    for i in filtered_y_test_indices:
        filtered_y_test.append(y_test[i])
        filtered_x_test.append(X_test[i])

    filtered_y_test = np.array(filtered_y_test)
    print(filtered_y_test)
    filtered_x_test = np.array(filtered_x_test)  

    # recode the y labels to be -1 and 1
    filtered_y_test = np.where(filtered_y_test == clothes1, -1, filtered_y_test)
    filtered_y_test = np.where(filtered_y_test == clothes2, 1, filtered_y_test)
    print(filtered_y_test)
#     print(filtered_x_test)
    
    return filtered_x_train, filtered_x_test, filtered_y_train, filtered_y_test

In [6]:
filtered_x_train, filtered_x_test, filtered_y_train, filtered_y_test = filter_datasets(X_train,X_test, y_train, y_test, t_shirt, pullover)

[0 0 0 ... 0 2 0]
[-1 -1 -1 ... -1  1 -1]
[2 2 0 ... 0 0 2]
[ 1  1 -1 ... -1 -1  1]


In [7]:
print(filtered_y_train.shape)
print(filtered_x_train.shape)
# print(filtered_y_train)

(12000,)
(12000, 784)


In [8]:
# initialise w = 0 (length of x train to occupy same dimensional space)
w = np.zeros(np.shape(filtered_x_train)[1])
print(w.shape)

(784,)


In [11]:
# # create while loop to iterate through data points
# # for loop to go through each data point in the data set
    
#     # calculate the dot product and compare with the label
#     # if misclassified add one to the counter
#     # update value of w and restart the program
# # stop the while loop when there are no misclassifications 

# # pass in training features and labels
def algorithm(w, X_train, y_train):
    m = 1
    
    while m!=0:
        # initiliase counter (m)
        m = 0
        
        # for each point in the X_train dataset
        for i in range(0, len(X_train)):
            
            # caclulate the dot product between it and w, multiply by the label and decide if the label is correct (>0) 
            # if incorrect (<= 0), update the value of w and start again
            if y_train[i] * np.dot(X_train[i], w) <= 0:
                # update m
                m += 1
                
                # update w
                if y_train[i] == 1:
                    w = w + X_train[i]
                else:
                    w = w - X_train[i]
            else:
                continue
            # go back to the beginning of the for loop            
    return w

In [12]:
w = algorithm(w, filtered_x_train, filtered_y_train)

KeyboardInterrupt: 

In [ ]:
# make predictions
def predict(w, X_test):
    y_pred = []
    
    for i in range(0,len(X_test)):
        # use dot product
        if np.dot(X_test[i], w) > 0:
            # if x lies above w, classify as 1
            y_pred.append(1)
         # what to do if it is exactly 0? 
        else:
            # currently assumes that if it falls on the line it is a -1 - shouldn't be the case?
            # if x lies below w, classify as -1
            y_pred.append(-1)
        
    return np.array(y_pred)

In [ ]:
def accuracy(y_test, y_pred):
    correct = 0
    incorrect = 0
    for i in range(0,len(y_test)):
        if y_test[i] == y_pred[i]:
            correct += 1
        else:
            incorrect += 1
            
    calc_accuracy = (correct/(incorrect + correct))*100
    return calc_accuracy

In [ ]:
y_pred = predict(w, filtered_x_test)

In [ ]:
calc_accuracy = accuracy(filtered_y_test, y_pred)
print(calc_accuracy)

In [ ]:
# print(w)
# print((y_pred == filtered_y_test).tolist())

## Accuracies:
Seemed to work fine using t_shirt and trousers but didn't seem to like any of the others, taking ages to converge or not converging at all
* t_shirt and trousers: 97.95%
* sandal and sneaker: *tried and seemed to take forever...*
* pullover and dress: *tried and seemed to take forever...*
* bag and ankle boot: 
* top and dress: 